version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - checkout
      - run: dotnet restore
      - run: dotnet build

